config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :merchant_locations, only: [:index, :show]
    resources :merchant_transactions, only: [:index, :show]
    resources :merchants, only: [:index, :show]
  end

  get '/' => 'merchant#new'
  post '/merchant' => 'merchant#create'
  get '/callback' => 'merchant#callback'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      admin_abilities(user)
    else
      user_abilities(user)
    end
  end

  def user_abilities(user)
    can [:new, :create], SquareConnection
  end

  def admin_abilities(user)
    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :merchant_locations, dependent: :destroy

  validates :access_token, presence: true, uniqueness: true

  after_create :fetch_merchant_locations

  def fetch_merchant_locations
    api = SquareConnect::LocationApi.new
    response = api.list_locations(access_token)

    locations = response.locations || []

    locations.each do |location|
      next if MerchantLocation.find_by_square_id(location.id)
      merchant_locations.create({
        square_id: location.id,
        name: location.name,
        timezone: location.timezone,
        address: location.address
      })
    end

    merchant_locations.each(&:fetch_merchant_transactions)
  end
end

app/models/merchant_location.rb
class MerchantLocation < ApplicationRecord
  belongs_to :merchant
  has_many :merchant_transactions, dependent: :destroy

  validates_presence_of :name, :square_id, :timezone

  after_create :fetch_merchant_transactions

  def fetch_merchant_transactions
    api = SquareConnect::TransactionApi.new
    response = api.list_transactions(merchant.access_token, square_id, {
      begin_time: 3.years.ago.to_datetime.rfc3339,
      end_time: Time.now.to_datetime.rfc3339
    })

    transactions = response.transactions || []
    transactions.each do |transaction|
      next if MerchantTransaction.find_by_square_id(transaction.id)

      merchant_transactions.create({
        merchant_location_id: transaction.location_id,
        square_id: transaction.id,
        transaction_date: transaction.created_at,
        product: transaction.product,
        amount_money: transaction.tenders,
        currency: transaction.tenders,
        processing_fee_money: transaction.tenders,
        notes: transaction.tenders,
      })
    end
  end

  def address=(value)
    value ||= {}
    write_attribute(:address, value.to_hash.values.join(', '))
  end
end

app/models/merchant_transaction.rb
class MerchantTransaction < ApplicationRecord
  belongs_to :merchant_location

  def notes=(tenders)
    write_attribute(:notes, tenders.map(&:note).join(','))
  end

  def currency=(tenders)
    write_attribute(:currency, tenders.first.amount_money.currency)
  end

  def amount_money=(tenders)
    write_attribute(:amount_money, tenders.inject(0){ |total, tender|  total += tender.amount_money.amount })
  end

  def processing_fee_money=(tenders)
    write_attribute(:processing_fee_money, tenders.inject(0){ |total, tender|  total += tender.processing_fee_money.amount })
  end
end

app/controllers/admin/merchant_locations_controller.rb
class Admin::MerchantLocationsController < ApplicationController
  def show
    @merchant_location = MerchantLocation.find_by_id(params[:id])
  end
end

app/controllers/admin/merchant_transactions_controller.rb
class Admin::MerchantTransactionsController < ApplicationController
  def index
  end

  def show
  end

  # TODO: Reporting on different years transactions

  # def report
  #   by_year = MerchantTransaction.all.group_by do |tr| DateTime.parse(tr.transaction_date).year end
  #   @transactions = by_year.each{ |year, trs| by_year[year] = trs.group_by{ |tr| DateTime.parse(tr.transaction_date).month } }
  # end
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < ApplicationController
  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/merchant_controller.rb
class MerchantController < ApplicationController
  def callback
    authorization = SquareAuthorization.authorize!(params['code'])

    if authorization.has_key?(:error)
      render plain: authorization[:error]
    else
      sandbox_access_token = Rails.application.config.sandbox_square_app_secret
      access_token = Rails.env.test? ? authorization[:access_token] : sandbox_access_token

      merchant = Merchant.find_or_create_by(access_token: access_token)
      merchant.fetch_merchant_locations
      render plain: "Access Token: #{access_token}"
    end
  end
end

app/helpers/admin/merchant_locations_helper.rb
module Admin::MerchantLocationsHelper
end

app/helpers/admin/merchant_transactions_helper.rb
module Admin::MerchantTransactionsHelper
end

app/helpers/admin/merchants_helper.rb
module Admin::MerchantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/merchant_helper.rb
module MerchantHelper
end

app/views/admin/merchant_locations/index.html.slim
h1 Admin::MerchantLocations#index
p Find me in app/views/admin/merchant_locations/index.html.slim

app/views/admin/merchant_locations/show.html.slim
.row
  .col-sm-6.offset-sm-1
    h1 = @merchant_location.name
.row
  .col-sm-11.offset-sm-1
    table.table.table-md
      thead
        tr
          th = 'Product'
          th = 'Amount of Money'
          th = 'Processing Fee'
          th = 'Currency'
          th = 'Notes'
          th = 'Transaction Date'
      tbody
        - @merchant_location.merchant_transactions.each do |transaction|
          tr
            th = transaction.product
            th = transaction.amount_money
            th = transaction.processing_fee_money
            th = transaction.currency
            th = transaction.notes
            th = transaction.transaction_date

app/views/admin/merchant_transactions/index.html.slim
h1 Transactions
.row
  .col-sm-6.col-sm-offset-3
    ul
      - @merchants.each do |merchant|
        h1 = merchant.token
        ul
          - merchant.merchant_locations.each do |location|
            = link_to location.name, admin_merchant_locations_show_url(location)

app/views/admin/merchant_transactions/show.html.slim
h1 Admin::MerchantTransactions#show
p Find me in app/views/admin/merchant_transactions/show.html.slim

app/views/admin/merchants/index.html.slim
.row
  .col-sm-6.offset-sm-1
    h1 Merchants
.row
  .col-sm-6.offset-sm-1
    ul
      - @merchants.each do |merchant|
        li
          p = merchant.access_token
          ul
            - merchant.merchant_locations.each do |location|
              li = link_to location.name, admin_merchant_location_path(location)

app/views/admin/merchants/show.html.slim
h1 Admin::Merchants#show
p Find me in app/views/admin/merchants/show.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Myapp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    = yield

app/views/merchant/new.html.slim
a.btn.btn-primary href="#{Rails.application.config.square_connect_host}/oauth2/authorize?client_id=#{Rails.application.config.square_app_id}" Connect